[build]
  command = "npm install && cd netlify/functions && npm install && cd ../../client && npm install --no-optional --no-audit && npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
